### ISSUE TITLE
Problem with AT Commands

### ISSUE THREAD

**Issue by augustopeterle** [insightsip/ISP4520-examples#20]
Hi!

I tried to run the at-commands example. I'm using the ISP4520-US on a custom board. The IDE that I use is Segger Embedded Studio.

So my question is, when I run the at-commands example the nrf52 goes to the 0xDEADBEEF and the BLE does not turn on. I did some tests and when I comment the at_manager_init() the BLE starts and I can scan the device with my smartphone.

Is there any suggestion about this ?

With this code below I was able to turn on the BLE.

`
  int main (void)
  {
      uint32_t err_code;
      uint32_t is_mac_processing_pending = 0;
	  
      // Initialize logs.
      log_init();
      NRF_LOG_INFO("BLE LoRa at commands application started.");
	  
      
      // Initialize clocks & timer
      nrf_drv_clock_init();
      nrf_drv_clock_lfclk_request(NULL);
      err_code = nrf_pwr_mgmt_init();
      APP_ERROR_CHECK(err_code);
      timers_init();
      
      
      // Initialize BLE
      ble_stack_init();
      gap_params_init();
      gatt_init();
      advertising_init();
      conn_params_init();
      services_init();
      //peer_manager_init();
  
      
      // Initialize LoRa chip.
      err_code = lora_hardware_init();
      APP_ERROR_CHECK(err_code);
      
      
      // Initialize AT commands manager
      //err_code = at_manager_init();
      //APP_ERROR_CHECK(err_code);
      
  
      // Start BLE
      err_code = ble_advertising_start(&m_advertising, BLE_ADV_MODE_FAST);
      APP_ERROR_CHECK(err_code);
      
      // Enter main loop.
      for (;;)
      {   
          
          /*
          // Process received AT command
          is_mac_processing_pending = at_manager_execute();
  
          if (!is_mac_processing_pending)
          {
              // Go to sleep mode
              if (NRF_LOG_PROCESS() == false)
              {
                  nrf_pwr_mgmt_run();
              }
          }*/
    }`

**Comment by Jonathan-fattouh** [comment]
Hello,
I suppose the UART (initialized in at_manager_init()) is messing something up.
Could you detail your setup? what hardware and how things are connected?

Best regards

**Comment by marcelluspereira** [comment]
Hi, ALL.
I can confirm the erratic behaviour. Commenting lines 479 and 480 of main.c file, the device is visible as a BLE beacon.
```
    // Initialize AT commands manager
    //err_code = at_manager_init();
    //APP_ERROR_CHECK(err_code);
```

However, trying to compile those lines gives me the following error:
```
<info> app: BLE LoRa at commands application started.
<info> app_timer: RTC: initialized.
<info> app: Initializing fds...
<info> app: Reading flash usage statistics...
<info> app: Found 0 valid records.
<info> app: Found 0 dirty records (ready to be garbage collected).
<debug> app: Fast advertising.
<error> app: AT_HAL_TRANSP_EVT_PHY_ERROR
<error> app: AT_HAL_TRANSP_EVT_PHY_ERROR
```
The board is a custom one, but have nothing fancy. It works with other examples. The major change is in the software, as I´m using it in Brazil, modifying the preprocessor definitions to (REGION_AU915), removing RegionUS915.c from building and adding RegionAU915.c.

Any ideias?

Thank you very much!

**Comment by Jonathan-fattouh** [comment]
Hello,

The AT command software uses UART on pin P0.08 (RX) and P0.06 (TX) to communicate with the host.
Since you are using a custom board, how are these pin connected to the host?
Are you using an UART to USB converter for example?

BR

**Comment by marcelluspereira** [comment]
I connect those pins directly to the MSP430. The curious thing is I have three boards working fine, but another three giving me this error.
I halt the MSP430 in the reset state and program the ISP4520. Just when I try to debug it (holding the msp430 reset state, all pins in Hi-Z), I receive those messages.
I double checked the board, bacause this one worked for some time! I just cleaned the build and reprogram it... and it´s not working anynmore.
I tracked the error, but I´m not really sure what can cause the UART not been initialized.

**Comment by Jonathan-fattouh** [comment]
> I halt the MSP430 in the reset state and program the ISP4520. Just when I try to debug it (holding the msp430 reset state, all pins in Hi-Z), I receive those messages.

So during your debug RX and TX are floating, which may cause unpredicted behaviour on RX pin and getting framing error on UART. Peharps some boards are more "noisy" and the nRF52 doesn't like when it initializes its UART.

Perhaps an idea for your solution would be: 
 - Start  your MPS430 initialization
 - Wait for your MP430 UART to be initialized  (the MPS430's TX should be high level now and not floating)
 - Reset the ISP4520 using its P0.21/RESET pin.

**Comment by marcelluspereira** [comment]
Yes, it seems to be working properly now.

Thank you very much, Jonathan!
