### ISSUE TITLE
continuous wave never stops

### ISSUE THREAD

**Issue by PaulAlexandreP** [insightsip/ISP4520-examples#26]
hello, I'm testing the continuous wave function (Radio.SetTxContinuousWave), in both projects: at-command and tx-cw, the sinus is generated but, it never stops.
In both project, I have the IRQ OnRadioTxTimeOut, but the sinus is still generating.
I use a ISP4520 Asia, on master version.

**Comment by Jonathan-fattouh** [comment]
Hello,
The time argument of RadioSetTxContinuousWave is in seconds (ant not in milliseconds).
In the tx-cw example the timeout is set to 3000 which makes 3000s (50min) of cw transmission, giving the impression of never stopping transmission.
This is obviously a mistake and the TX_TIMEOUT define should be changed from 3000 to 3.

**Comment by PaulAlexandreP** [comment]
I already notice that, I put 20 instead of 3000 to avoid waiting.

**Comment by PaulAlexandreP** [comment]
Have you got the same problem on your side ? I can't stop the continuous wave once I start it, even if I put a small number (ie: 20)

**Comment by Jonathan-fattouh** [comment]
Add Radio.Sleep(); or Radio.Standby(); in the tx tipeout callback.
example in main.c
```
void OnRadioTxTimeout(void)
{
    NRF_LOG_INFO("OnRadioTxTimeout");
    Radio.Standby();
}
```

**Comment by PaulAlexandreP** [comment]
The fix stops the generation of the wave after the timeout, but I need it in the at_command project.
In that case, the sinus stops, but the function LmHandlerJoinRequest2 returns LORAMAC_STATUS_BUSY when I ask a join request. FYI I wait the timeout of the continuous wave generation before asking the join request.

**Comment by PaulAlexandreP** [comment]
Have you got an idea on how I can fix the busy status ?

**Comment by Jonathan-fattouh** [comment]
How do you start a cw generation in the at command project? 
I don't see any AT command for it.

**Comment by PaulAlexandreP** [comment]
I have created a command which calls Radio.SetTxContinuousWave during one minute. Once the wave stops, if I call LmHandlerJoinRequest2, the function returns a busy status

**Comment by Jonathan-fattouh** [comment]
Does your command call directly Radio.SetTxContinuousWave or using mlme request?
```
MlmeReq_t mlmeReq;
mlmeReq.Type = MLME_TXCW;
mlmeReq.TTimeout = ...
mlmeReq.TFrequency = ....
mlmeReq.TPower = ...
LoRaMacMlmeRequest( &mlmeReq );
```
Anyhow I need to test in our lab to be able to observe the issue, I'll get back to you when I find a solution

**Comment by PaulAlexandreP** [comment]
I call the function: LoRaMacStatus_t SetTxContinuousWave( uint16_t timeout, uint32_t frequency, uint8_t power )
which calls Radio.SetTxContinuousWave and put the MacState to LORAMAC_TX_RUNNING.
So no, I don't use a mlme request. On my side, I will try with a mlme request.

**Comment by Jonathan-fattouh** [comment]
I have added this commad in my at example
at_error_code_t at_cw_set(const uint8_t *param)
```
{
    MlmeReq_t mlmeReq;
    mlmeReq.Type = MLME_TXCW;
    mlmeReq.Req.TxCw.Timeout = 3;
    mlmeReq.Req.TxCw.Frequency = 868000000;
    mlmeReq.Req.TxCw.Power = 0;
    LoRaMacMlmeRequest( &mlmeReq );
    return AT_OK;
}
```
When sending AT+CW i observe a signal during 3sec on the spectrum analyzer.
During the cw duration the device responds by ERROR_BUSY and join request.
After the cw duration the device is no longer busy and respond by OK to join request.

When calling directly SetTxContinuousWave:
```
at_error_code_t at_cw_set(const uint8_t *param)
{
    SetTxContinuousWave(3, 868000000, 0);
    return AT_OK;
}
```

I'm stuck in ERROR_BUSY

Conclusion: please use mlme request

**Comment by PaulAlexandreP** [comment]
I tested on my side, it's OK now. Thanks for the help.
