### ISSUE TITLE
isp4520-EU and isp4520-US dont see packets Lora or LoRaWan on the Semtech SX1302CSS868GW1 gateway

### ISSUE THREAD

**Issue by techsd** [insightsip/ISP4520-examples#42]
Greetings. 
I have taken the isp4520-EU and isp4520-US modules for a project.
examples from the beginning took from here :
insightsip.com/fichiers_insightsip/pdf/ble/ISP4520/ISP4520_Source_Code.zip
then when it didn't work, he sees Lora or LoRaWan packets on the Semtech SX1302CSS868GW1 gateway.
I took it here
github.com/insightsip/ISP4520-examples
I faced a problem - the Semtech SX1302CSS868GW1 gateway does not see Lora or LoRaWan packets from the isp4520 module
I took the default JSON settings for the Semtech SX1302CSS868GW1 gateway from github.com/Lora-net/sx1302_hal/tree/master/packet_forwarder
I ask for help in configuring the isp4520-EU module for the Semtec SX1302CSS868GW1 gateway to forward Lora or LoRaWan packets

**Comment by vAnArhist** [comment]
> Greetings. I have taken the isp4520-EU and isp4520-US modules for a project. examples from the beginning took from here : insightsip.com/fichiers_insightsip/pdf/ble/ISP4520/ISP4520_Source_Code.zip then when it didn't work, he sees Lora or LoRaWan packets on the Semtech SX1302CSS868GW1 gateway. I took it here github.com/insightsip/ISP4520-examples I faced a problem - the Semtech SX1302CSS868GW1 gateway does not see Lora or LoRaWan packets from the isp4520 module I took the default JSON settings for the Semtech SX1302CSS868GW1 gateway from github.com/Lora-net/sx1302_hal/tree/master/packet_forwarder I ask for help in configuring the isp4520-EU module for the Semtec SX1302CSS868GW1 gateway to forward Lora or LoRaWan packets

Also, as You mensioned before, you have EU gateway, but using it with isp4520-US? In that case it can be main problem, as it simply works on different frequency plans.
