### ISSUE TITLE
some files missing in SDK

### ISSUE THREAD

**Issue by alexlbc3** [insightsip/ISP4520-examples#9]
Hi,
Impossible to compile the project on  develop branch, some files are not found in the SDK like nrf.h or compiler_abstraction.h

Regards,
Alex

**Comment by Jonathan-fattouh** [comment]
Hello,
Does   #11 fix your problem?
Some projects were indeed broken but for different files...
Regards,
Jonathan

**Comment by alexlbc3** [comment]
Hello,
yes #11  fix my problem.
Thank for your help
Regards,
Alex
